[changelog]
header = ""
body = """
{%- if version %}
  {{- version }}
  {% for commit in commits | filter(attribute="breaking", value=true) -%}
    {%- if loop.first %}
      ### Breaking Changes

    {% endif -%}
    - {{ commit.breaking_description }}
  {% endfor %}
  {% for group, commits in commits | group_by(attribute="group") -%}
    {% for commit in commits | sort(attribute="scope") -%}
      {%- if loop.first %}
        ### {{ group | split(pat=" ") | slice(start=1) | join(sep=" ") }}

      {% endif -%}
      - {{ commit.id }} \
        {% if commit.scope != "" -%}
          **{{ commit.scope ~ ":" }}** \
        {%- endif -%}
        {{ commit.message }}
    {% endfor -%}
  {% endfor %}
{%- endif -%}
"""
footer = ""
trim = true

[git]
conventional_commits = true
commit_preprocessors = [
  { pattern = "\\s*\\[skip ci\\]", replace = "" },
]
commit_parsers = [
  { message = "^feat", group = "1 Features", default_scope = "" },
  { message = "^fix", group = "2 Bug Fixes", default_scope = "" },
  { message = "^perf", group = "3 Performance Improvements", default_scope = "" },
  { message = ".*", skip = true },
]
protect_breaking_commits = true
tag_pattern = "v*.*.*"
